### ISSUE TITLE
Code unable to find config.json

### ISSUE THREAD

**Issue by bkmulusew** [datastax/cdc-apache-cassandra#169]
Hello, I followed the documentation on the DataStax website on how to connect my local machine to DataStax's Cassandra database using a java-driver, but I'm getting the following error:

Exception in thread "main" java.lang.IllegalStateException: Invalid bundle: missing file config.json
at com.datastax.oss.driver.internal.core.config.cloud.CloudConfigFactory.createCloudConfig(CloudConfigFactory.java:114)
at com.datastax.oss.driver.api.core.session.SessionBuilder.buildDefaultSessionAsync(SessionBuilder.java:876)
at com.datastax.oss.driver.api.core.session.SessionBuilder.buildAsync(SessionBuilder.java:817)
at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:835)
at com.telusko.AstraJavaDemo.ConnectDatabase.main(ConnectDatabase.java:16)

Any ideas on how to resolve this problem?

**Comment by aymkhalil** [comment]
I gather you are trying to connect to Astra DB? In that case please follow the steps here: https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-java.html

Btw this is not the right forum for Astra DB questions - the project adds CDC support to on-prem OSS and DSE flavors of Cassandra

**Comment by bkmulusew** [comment]
What is the right forum for asking Astra DB questions?
