### ISSUE TITLE
Cannot deploy the CSC before the keyspace exists

### ISSUE THREAD

**Issue by vroyer** [datastax/cdc-apache-cassandra#7]
Cannot deploy the CSC before the keyspace exists because of a NoClassDefFoundError. 

```
21:42:26.076 [s0-admin-0] INFO  com.datastax.oss.driver.internal.core.time.Clock - Using native clock for microsecond precision
21:42:26.397 [s0-admin-0] INFO  com.datastax.oss.driver.internal.core.session.DefaultSession - [s0] Negotiated protocol version V4 for the initial contact point, but cluster seems to support V5, keeping the negotiated version
21:42:26.880 [public/default/cassandra-source-ks1.table1-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - Source open produced uncaught exception:
com.datastax.oss.driver.api.core.InvalidKeyspaceException: Invalid keyspace ks1
	at com.datastax.oss.driver.api.core.InvalidKeyspaceException.copy(InvalidKeyspaceException.java:34) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:773) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.cdc.CassandraClient.buildCqlSession(CassandraClient.java:132) ~[source-0.1.0.jar:?]
	at com.datastax.oss.cdc.CassandraClient.<init>(CassandraClient.java:81) ~[source-0.1.0.jar:?]
	at com.datastax.oss.pulsar.source.CassandraSource.open(CassandraSource.java:92) ~[source-pulsar-0.1.0.jar:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupInput(JavaInstanceRunnable.java:720) ~[?:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:215) ~[?:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:235) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
21:42:26.884 [public/default/cassandra-source-ks1.table1-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [public/default/cassandra-source-ks1.table1:0] Uncaught exception in Java Instance
com.datastax.oss.driver.api.core.InvalidKeyspaceException: Invalid keyspace ks1
	at com.datastax.oss.driver.api.core.InvalidKeyspaceException.copy(InvalidKeyspaceException.java:34) ~[?:?]
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149) ~[?:?]
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:773) ~[?:?]
	at com.datastax.oss.cdc.CassandraClient.buildCqlSession(CassandraClient.java:132) ~[?:?]
	at com.datastax.oss.cdc.CassandraClient.<init>(CassandraClient.java:81) ~[?:?]
	at com.datastax.oss.pulsar.source.CassandraSource.open(CassandraSource.java:92) ~[?:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupInput(JavaInstanceRunnable.java:720) ~[org.apache.pulsar-pulsar-functions-instance-2.7.2.1.0.0.jar:2.7.2.1.0.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:215) ~[org.apache.pulsar-pulsar-functions-instance-2.7.2.1.0.0.jar:2.7.2.1.0.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:235) ~[org.apache.pulsar-pulsar-functions-instance-2.7.2.1.0.0.jar:2.7.2.1.0.0]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
21:42:26.890 [public/default/cassandra-source-ks1.table1-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Closing instance
21:42:26.892 [public/default/cassandra-source-ks1.table1-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Unloading JAR files for function InstanceConfig(instanceId=0, functionId=92b1dd26-6010-44bf-8062-9dc02ad4564c, functionVersion=89125897-5067-4dca-9117-aabb63aabbbb, functionDetails=tenant: "public"
namespace: "default"
name: "cassandra-source-ks1.table1"
className: "org.apache.pulsar.functions.api.utils.IdentityFunction"
autoAck: true
parallelism: 1
source {
  className: "com.datastax.oss.pulsar.source.CassandraSource"
  configs: "{\"loadBalancing.localDc\":\"northeurope\",\"keyspace\":\"ks1\",\"auth.password\":\"cassandra\",\"events.topic\":\"persistent://public/default/events-default-ks1.table1\",\"contactPoints\":\"cndb-coordinator.cndb-dev.svc.cluster.local\",\"events.subscription.name\":\"sub1\",\"auth.provider\":\"PLAIN\",\"value.converter\":\"com.datastax.oss.pulsar.source.converters.AvroConverter\",\"key.converter\":\"com.datastax.oss.pulsar.source.converters.AvroConverter\",\"auth.username\":\"cassandra\",\"table\":\"table1\"}"
  typeClassName: "org.apache.pulsar.client.api.schema.GenericRecord"
  builtin: "cassandra-source"
}
sink {
  topic: "persistent://public/default/data-ks1.table1"
  typeClassName: "org.apache.pulsar.client.api.schema.GenericRecord"
  forwardSourceMessageProperty: true
}
resources {
  cpu: 1.0
  ram: 1073741824
  disk: 10737418240
}
componentType: SOURCE
, maxBufferedTuples=1024, functionAuthenticationSpec=null, port=38475, clusterName=pulsar, maxPendingAsyncRequests=1000)
21:42:26.892 [main] INFO  org.apache.pulsar.functions.runtime.JavaInstanceStarter - RuntimeSpawner quit, shutting down JavaInstance
21:42:26.894 [main] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://10.240.0.8:6650
21:42:57.519 [s0-admin-1] WARN  io.netty.util.concurrent.DefaultPromise - An exception was thrown by com.datastax.oss.driver.internal.core.util.concurrent.Reconnection$$Lambda$372/0x00000008404c8c40.operationComplete()
java.lang.NoClassDefFoundError: com/datastax/oss/driver/internal/core/util/Loggers
	at com.datastax.oss.driver.internal.core.util.concurrent.Reconnection.lambda$scheduleNextAttempt$2(Reconnection.java:198) ~[java-driver-core-4.11.0.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[java-instance.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[java-instance.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[java-instance.jar:?]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[java-instance.jar:?]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[java-instance.jar:?]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109) ~[java-instance.jar:?]
	at io.netty.util.concurrent.PromiseTask.setFailureInternal(PromiseTask.java:131) ~[java-instance.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:190) ~[java-instance.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[java-instance.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[java-instance.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[java-instance.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[java-instance.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.datastax.oss.driver.internal.core.util.Loggers
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
```

**Comment by vroyer** [comment]
Resolved, the source connector crashed and restart later until the keyspace/table exists.
