### ISSUE TITLE
Connector flaky test: PulsarCassandraSourceTests#testConnectionFailure

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/cdc-apache-cassandra#72]
```
PulsarCassandraSourceTests > testConnectionFailure() FAILED
    org.opentest4j.AssertionFailedError: expected: <3> but was: <0>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
        at app//com.datastax.oss.pulsar.source.PulsarCassandraSourceTests.testConnectionFailure(PulsarCassandraSourceTests.java:804)
```

https://github.com/datastax/cdc-apache-cassandra/runs/6654630390?check_suite_focus=true

**Comment by darkmatter18** [comment]
I tested the flaky test **10 times**, but I was unable to reproduce the issue.

Test Setup information:

- **System** - Apple Silicon M4
- **OS** - Mac OS X
- **Java** - Oracle OpenJDK 17.0.12 - aarch64
- **CDC Version** - v2.3.2

Additionally, the following Continuous Integration (CI) tests also passed.

- https://github.com/datastax/cdc-apache-cassandra/actions/runs/16569902657
- https://github.com/datastax/cdc-apache-cassandra/actions/runs/16569884325
- https://github.com/datastax/cdc-apache-cassandra/actions/runs/16569872391
