### ISSUE TITLE
Flaky test: PulsarSingleNodeTests.testInvalidSchema

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/cdc-apache-cassandra#73]
```
PulsarSingleNodeDse4Tests > testInvalidSchema() FAILED
    java.lang.AssertionError: Expecting one message, check the agent log
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at com.datastax.oss.cdc.PulsarSingleNodeTests.testInvalidSchema(PulsarSingleNodeTests.java:432)
```
https://github.com/datastax/cdc-apache-cassandra/runs/6776506504?check_suite_focus=true

**Comment by darkmatter18** [comment]
I tested the flaky test **10 times**, but I was unable to reproduce the issue.

Test Setup information:

- **System** - Apple Silicon M4
- **OS** - Mac OS X
- **Java** - Oracle OpenJDK 17.0.12 - aarch64
- **CDC Version** - v2.3.2

Additionally, the following Continuous Integration (CI) tests also passed.

- https://github.com/datastax/cdc-apache-cassandra/actions/runs/16569902657
- https://github.com/datastax/cdc-apache-cassandra/actions/runs/16569884325
- https://github.com/datastax/cdc-apache-cassandra/actions/runs/16569872391
